name: Deployment

concurrency: Production

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    environment:
      description: "Environment to deploy"
      type: environment
      required: true

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://nft-lotto.vercel.app
    env:
      VITE_ALCHEMY_ID: ${{ vars.VITE_ALCHEMY_ID }}
      VITE_RPC_URL: ${{ vars.VITE_RPC_URL }}
      VITE_CHAIN_ID: ${{ vars.VITE_CHAIN_ID }}
      VITE_LOTTO_CONTRACT_ADDRESS: ${{ vars.VITE_LOTTO_CONTRACT_ADDRESS }}
      VITE_IS_PROD: ${{ vars.VITE_IS_PROD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Setup Turbo cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1.1.0

      - name: Install
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./
